GET http://localhost:8000/api/v1/memories

###

POST http://localhost:8000/api/v1/memories
Content-Type: application/json

{
    "name": "Lake Julian",
    "description": "Boat ride",
    "message": "Family Fun"
}

###

GET http://localhost:8000/api/v1/memories/63c7215e056cbbf87f8bcf16

###

DELETE  http://localhost:8000/api/v1/memories/63c6a101229612c0e1543429

###

PATCH http://localhost:8000/api/v1/memories/63c6c91ec97b72200fe4e5b5
Content-Type: application/json

{
    "name": "Trisha",
    "description": "WDV1",
    "message": "Testing"
}