GET http://localhost:8000/api/v1/memories

###

POST http://localhost:8000/api/v1/memories
Content-Type: application/json

{
    "name": "Lake h",
    "description": "Boat ride",
    "message": "Family Fun"
}

###

GET http://localhost:8000/api/v1/memories/63d53f14e735b0f874a8a10b

###

DELETE  http://localhost:8000/api/v1/memories/63c6a101229612c0e1543429

###

PATCH http://localhost:8000/api/v1/memories/63d53f14e735b0f874a8a10b
Content-Type: application/json

{
    "name": "Tisha",
    "description": "WDV1",
    "message": "Testing"
}